frase = input('Digite uma frase: ').strip()
frase = frase.upper()
print('A letra A aparece na frase {} vezes'.format(frase.count('A')))
print('A letra A teve sua primeira aparição na posição {}'.format(frase.find('A')+1))
print('A letra A teve sua última aparição na posição {}'.format(frase.rfind('A')+1))
